spring.application.name=bARTle



#Configurations BDD (H2)
# afficher le sql genere par JPA
spring.jpa.show-sql=true

#
#H2 doit etre importee en dependance
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console doit etre importee en dependance : https://stackoverflow.com/a/79796353
# rendre accessible la BDD par un console web
spring.h2.console.enabled=true
#la console web est sur le path /h2
spring.h2.console.path=/h2